name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Deploy the Docker image
      run: |
          docker build -t testmycregistry.azurecr.io/web-telegram-bot:latest .
          docker login testmycregistry.azurecr.io --username testmycregistry --password rlumPJ09gp2CqP6xjGTDy/DEBmNyM19y
          docker push testmycregistry.azurecr.io/web-telegram-bot:latest
